trigger:
- main //please change the branch name according to the branch configured in AB

pool:
  vmImage: ubuntu-latest //please change the vmImage name according to the image configured in AB

jobs:
- deployment: TalosTS
  displayName: 'TalosTS'
  environment: 'testing-vm' //please change this environment name according to the environment configured in AB
  strategy:
    runOnce:
      deploy:
        steps:
        - script: | 
            apiRes=$(curl --silent --write-out "HTTPSTATUS:%{http_code}" -X POST "https://d08ue0201.ac.lp.acml.com/talos/external/executeTestSet" -H "accept: */*" -H "apiKey: 355c88a4-9160-432d-b6da-a69628765560" -H "secretKey: bad9cf2b-cb70-42a7-badb-9bfc54766f0c" -H "Content-Type: application/json" -d "{\"projectId\": 1,\"testSetId\": 1,\"loggedUserName\": \"Org_Admin\",\"triggeredFromApp\": \"Talos\",\"maxNumberOfThreads\": 5,\"atopApiUrl\": \"https://d08ue0201.ac.lp.acml.com/atop/api/v1/\", \"talosApiUrl\": \"https://d08ue0201.ac.lp.acml.com/talos/\"}")
            apiResBody=$(echo $apiRes | sed -e 's/HTTPSTATUS\:.*//g')
            apiResStatus=$(echo $apiRes | tr -d '\n' | sed -e 's/.*HTTPSTATUS://')
            echo "Test suite execution response is $apiResBody"
            echo "Test suite execution status code is $apiResStatus"